### ISSUE TITLE
aarch64 should use arm64 version

### ISSUE THREAD

**Issue by XZiar** [v2ray/install#1]
https://github.com/v2ray/install/blob/a38194fb348a321c3f80ab0d5a404d62bd0f65a0/go.sh#L103

On some arm64 plaforms, `uname -m` will return `aarch64`.
The script does not contain judgement for it and it will download the deafult --- amd64 version.

Maybe this line should be changed to 
`elif [[ "$ARCH" == *"armv8"* ]] || [[ "$ARCH" == *"aarch64"* ]]; then`

**Comment by Cwek** [comment]
fork it, modify it, and repush the new one.

**Comment by DarienRaymond** [comment]
已更新
